# Generated by Django 4.2.2 on 2023-08-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_creditcard_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('master', 'Master Card'), ('visa', 'Visa Card'), ('verve', 'Verve Card')], default='master', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.IntegerField(max_length=20),
        ),
    ]
