# Generated by Django 4.2.2 on 2023-07-01 13:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=30, region=None),
        ),
    ]
