# Generated by Django 4.2.2 on 2023-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='mobile',
            field=models.CharField(max_length=1000),
        ),
    ]
